### ISSUE TITLE
Whiskermenu一部表記が英語になっている

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#10]
xfce4-popup-whiskermenuコマンドやWindowsキーなどで起動するメニューのSettingsのみ英語表記です。

![image](https://user-images.githubusercontent.com/50263013/103153750-0fe26200-47d6-11eb-9034-7fe12aa78b4c.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
garconの問題です。
hookで対処しました。

**Comment by naoko1010hh** [comment]
日本語になって違和感に気づきました 管理と設定は統合スべきかもしれません内容的に
![VirtualBox_Serene F _29_12_2020_20_25_14](https://user-images.githubusercontent.com/50263013/103280727-705ee280-4a14-11eb-9722-d1536e1e2bd7.png)

使用ISO kokkiemouse内部ビルド
SereneLinux-33-serene-ja-2020.12.29-ea2246c-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
上流の問題です。
