### ISSUE TITLE
ThunarのサイドペインにXDGのディレクトリが設定されていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#11]
XDGのディレクトリがThunar左側のサイドペインに設定されていないのは不親切です。
可能であれば修正お願いします

![image](https://user-images.githubusercontent.com/50263013/103153962-d90d4b80-47d7-11eb-88d7-0ce42a61310f.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
う〜ん
ソースコード見たわけではないですが多分不可能です。

**Comment by naoko1010hh** [comment]
ここのプロジェクトで書くべきではありませんが同じFascodeNetworkが開発しているAlter Linuxこの問題を解決していると思われます。
https://twitter.com/Hayao0819/status/1343011284560748545
https://github.com/FascodeNet/alterlinux/issues/229

**Comment by mineyoshikawasnow** [comment]
よしそれを使おう。

**Comment by mineyoshikawasnow** [comment]
![picture](https://user-images.githubusercontent.com/39451248/103272574-94b0c400-4a00-11eb-9769-f0e219124b63.png)
fixed!
ea2246c
