### ISSUE TITLE
VLC・Serene-Setup-Wizard・meditがインストールされていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#12]
下部のパネルタスクバーのランチャーから起動することができない 
vlcがインストールされていないため
![image](https://user-images.githubusercontent.com/50263013/103154110-c8a9a080-47d8-11eb-9fac-c24f599f7b7f.png)

xfce4-popup-whiskermenuの管理のSerene-Setup-Wizardを起動することができない
Serene-Setup-Wizardがインストールされていないため
![image](https://user-images.githubusercontent.com/50263013/103154213-47064280-47d9-11eb-94d5-605f09ee68a7.png)
![image](https://user-images.githubusercontent.com/50263013/103154225-571e2200-47d9-11eb-8b80-7f3e73fa38cc.png)

下部のパネルタスクバーのランチャーから起動することができない 
meditがインストールされていないため
![image](https://user-images.githubusercontent.com/50263013/103154376-5fc32800-47da-11eb-8004-174f0a4e29e8.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
e2a2ebで修正済み
