### ISSUE TITLE
インストール後起動することができない。

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#13]
インストール後起動することができない。致命的すぎる。

![image](https://user-images.githubusercontent.com/50263013/103162908-291cfa00-483a-11eb-9744-6452e7c08501.png)

VirtualBoxの環境↓
![image](https://user-images.githubusercontent.com/50263013/103162925-58cc0200-483a-11eb-839b-da54c54e9429.png)
![image](https://user-images.githubusercontent.com/50263013/103162954-c0824d00-483a-11eb-955d-27773d80a9f2.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
チ　ッ　プ　セ　ッ　ト　設　定　の　問　題　
そ　れ　か　S　E　L　I　N　U　X

**Comment by mineyoshikawasnow** [comment]
これだけじゃ原因不明なので
もっと詳細なログがほしい。..

**Comment by naoko1010hh** [comment]
了解別な作業終えたら取れるところスクショ撮ってくる

**Comment by mineyoshikawasnow** [comment]
う〜んと
おそらくBIOS限定の問題

**Comment by mineyoshikawasnow** [comment]
嘘ですEFIでも起きました

final-process書き換えたので次回ビルドでおそらく治ります。

**Comment by mineyoshikawasnow** [comment]
![image](https://user-images.githubusercontent.com/39451248/103173409-2e139500-489e-11eb-862d-443febc6b657.png)
2020 12/27 21時ビルドでインスコできたのでcloseします。
