### ISSUE TITLE
UEFI環境で起動しない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#14]
UEFI環境で起動するのか検証するために下記の画像のように起動することができない
UEFIにチェックを入れて起動しようとしたところ

![image](https://user-images.githubusercontent.com/50263013/103165250-a6effe00-4858-11eb-930c-8eb8f5018f1f.png)
この画面で起動しない
![image](https://user-images.githubusercontent.com/50263013/103165227-5c6e8180-4858-11eb-90ff-651454edabbc.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ起動途中

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
![image](https://user-images.githubusercontent.com/39451248/103172936-a2e4d000-489a-11eb-995e-c48446258d2b.png)
2020 12/27の21時のビルドにて正常動作したので閉じます。

**Comment by naoko1010hh** [comment]
クローズのところ申し訳ないです。
![VirtualBox_Serene F  のクローン_28_12_2020_23_04_23](https://user-images.githubusercontent.com/50263013/103219450-19e49c00-4961-11eb-8451-cc32548a3bce.png)
内部ビルドの 
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso でも発生したのですがこれはこちら側の環境の問題でしょうか？

**Comment by mineyoshikawasnow** [comment]
https://github.com/FascodeNet/LFBS/commit/7bcb89df4f2c50d202758355712de04944b1e8d0
