### ISSUE TITLE
VirtualBox ライブ起動 plymouthアニメーションがない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#16]
ライブ起動時などに表示されるはずのplymouthアニメーションが表示されません。
新ベータリリースに向けて何かしらのアニメーションは必要でしょう。
UEFIじゃない方の画面で表示されました
起動することはできますが可能であれば何かしらアニメーションがあったほうが良いのではないでしょうか？

OSインストールが正常に表示されます。

![VirtualBox_Serene F _28_12_2020_22_48_05](https://user-images.githubusercontent.com/50263013/103218807-734bcb80-495f-11eb-966e-7dcb1f6ba972.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso

検証環境　仮想　ライブ起動途中

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso
正常に動作しましたが....
![image](https://user-images.githubusercontent.com/39451248/103219085-1997d100-4960-11eb-91f3-0a79bb946e4f.png)

**Comment by naoko1010hh** [comment]
もしかしてvirtualBOX限定の問題でしょうか？

**Comment by mineyoshikawasnow** [comment]
そうだと思います。

**Comment by mineyoshikawasnow** [comment]
いやBIOS艦橋ではだめでした。。。
おそらく画面ドライバの問題でしょう...

**Comment by mineyoshikawasnow** [comment]
カーネルオプションの問題でした

**Comment by mineyoshikawasnow** [comment]
https://github.com/FascodeNet/LFBS/commit/84771f0ec16dda5b98e0ff6088d1fe22df845163

**Comment by mineyoshikawasnow** [comment]
治ってたのでclose
