### ISSUE TITLE
Flast Nightly既定ブラウザーに設定されていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#17]
ライブ起動行いFlastブラウザーのデバックを行おうと起動したところ下記のように表示されてしまい

SereneLinuxのデフォルトブラウザーにも関わらず既定ブラウザーに設定されていないのはユーザーが戸惑うのではないでしょうか？

![VirtualBox_Serene F  のクローン_28_12_2020_22_52_14](https://user-images.githubusercontent.com/50263013/103219627-97101100-4961-11eb-8223-e967f7a944b6.png)
kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
されてなきゃGoogleショートカット使えないんだよなぁ....

**Comment by naoko1010hh** [comment]
お気に入りアプリケーション設定されているためショートカット系は起動することはできるみたいです。

**Comment by mineyoshikawasnow** [comment]
https://github.com/FascodeNet/LFBS/commit/f024bd4e7a6c784ce959078706c4f1cee71514b8

**Comment by mineyoshikawasnow** [comment]
xfceのルール上だとexo-browserがデフォルトです。
exo-browserはflastにリンクされてるので....
