### ISSUE TITLE
ロック画面がWebkit-greeterではない/背景がSereneLinuxのものではない。

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#18]
開発チャットですでにWebkit-greeter がロック画面に反映されてるとのことでしたが反映されていなかったためご報告させたいただきます。
下記のスクリーンショットはUEFIじゃない方おそらくBIOSかな？それでインストールしたあと起動した画面です
背景画像もSereneLinuxの背景ではありませんし、Webkit-greeterじゃないためバグかと思われます。

![VirtualBox_Serene F3_28_12_2020_22_50_53](https://user-images.githubusercontent.com/50263013/103220126-d3903c80-4962-11eb-8638-9ff35eaf8989.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso

検証環境　仮想　インストール後のログイン画面

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
う〜んこの...
liveでユーザー切り替えしてみて
ISOの問題かCalaramaresか確かめたいので

**Comment by naoko1010hh** [comment]
了解

**Comment by mineyoshikawasnow** [comment]
あとcat /etc/lightdm/lightdm-webkit2-greeter.conf
の結果も欲しいです///

**Comment by naoko1010hh** [comment]
![VirtualBox_Serene F _28_12_2020_23_49_21](https://user-images.githubusercontent.com/50263013/103223070-ce35f080-4968-11eb-93d2-7a3d0300321a.png)
[lightdm-webkit2-greeter.conf.txt](https://github.com/FascodeNet/LFBS/files/5747735/lightdm-webkit2-greeter.conf.txt)

**Comment by naoko1010hh** [comment]
どぞ

**Comment by mineyoshikawasnow** [comment]
よっしゃー！ｳﾏｸｲｯﾀｧｧｧ!!!
iso -> SereneLinux-33-serene-ja-2020.12.28-0ff4d4f-x86_64.iso
![image](https://user-images.githubusercontent.com/39451248/103249874-96549a80-49b4-11eb-9570-074c56eb527b.png)
