### ISSUE TITLE
powerline-go 縦幅がはみ出している

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#19]
ターミナルにバグがないか検証するためにxfce4-terminalをタスクバーから起動したところpowerline-goのデザインがおかしいことに気づきホストPCのAlter Linuxを参照したところやはり縦幅がはみ出している？ことがわかったのでご報告させていただきます。

ライブ環境
![VirtualBox_Serene F _28_12_2020_23_34_37](https://user-images.githubusercontent.com/50263013/103221166-55816500-4965-11eb-9f50-7c05632a8ce2.png)
インストール後
![VirtualBox_Serene F3_28_12_2020_23_33_02](https://user-images.githubusercontent.com/50263013/103221157-4c909380-4965-11eb-8d64-9f6d6c8166f1.png)

Alter Linuxのターミナルのpowerline-go
![image](https://user-images.githubusercontent.com/50263013/103221286-9d07f100-4965-11eb-8f2e-148851fafcbc.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso

検証環境　仮想　インストール後のデスクトップ、ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
適切なフォントがなかったのでこうなりました...

**Comment by mineyoshikawasnow** [comment]
治ったのでclose
![image](https://user-images.githubusercontent.com/39451248/103261657-93be6900-49e5-11eb-8d97-637de030c341.png)

**Comment by naoko1010hh** [comment]
ハッシュ忘れずに記述してください。

**Comment by mineyoshikawasnow** [comment]
isoは565d19b

**Comment by mineyoshikawasnow** [comment]
修正commitは 9f3c7d5
