### ISSUE TITLE
Calamares 日本語を選択したのにタイムゾーンが自動選択されない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#20]

**Comment by kokkiemouse** [comment]
?

**Comment by naoko1010hh** [comment]
ミス　すぐに情報追加する開業のつもりでエンター押したら投稿しても歌

**Comment by naoko1010hh** [comment]
日本語を選択したら自動で日本に選択したほうがユーザーエクスペリエンスが向上するのではないでしょうか？

![VirtualBox_Serene F _29_12_2020_20_39_20](https://user-images.githubusercontent.com/50263013/103281596-8e2d4700-4a16-11eb-8c69-f837fc48d767.png)
![VirtualBox_Serene F _29_12_2020_20_39_27](https://user-images.githubusercontent.com/50263013/103281594-8cfc1a00-4a16-11eb-954f-60d94a43223e.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.29-ea2246c-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
I see.

**Comment by mineyoshikawasnow** [comment]
![image](https://user-images.githubusercontent.com/39451248/103287728-a016e600-4a26-11eb-8eb5-75ed4c94e32b.png)
修正しました。
df28f87
