### ISSUE TITLE
googleショートカットアイコン正常に動作せず

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#23]
xfce4-whisker-menuの内部にあるgoogle系のショートカットが正常に動作しない模様
詳細は後日追記します

https://youtu.be/12yr2K4xPA4?t=503

**Comment by mineyoshikawasnow** [comment]
LUBS Fの問題ではなく
serene-google-menusの問題です。

**Comment by naoko1010hh** [comment]
Firefoxへブラウザ変更の影響で同様の問題が発生しています。
![スクリーンショット_2021-04-04_00-19-20](https://user-images.githubusercontent.com/50263013/113483299-a9a86200-94dd-11eb-9ed4-1602ad5ea107.png)

検証ISO 内部バージョン
SereneLinux-34-serene-ja-2021.04.03-f37cb43-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 2GB
仮想VDI 8GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
exo-open使うようにしました
