### ISSUE TITLE
build.shで未定義の関数が呼び出される

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/LFBS#26]
./build.shにオプションを付けた状態で実行してビルドしようとすると、./build.sh: 行 168: msg_debug: コマンドが見つかりません　とエラーが出て動作しない。オプションを付けていない状態で実行すると途中まで動作しますが、パッケージのインストールが終了した段階で同様のエラーが発生します。

![image](https://user-images.githubusercontent.com/59412454/106148798-d6c65480-61bc-11eb-897c-0330176780bc.png)
![image](https://user-images.githubusercontent.com/59412454/106148841-e2198000-61bc-11eb-9f9b-e15bb9402abf.png)

**Comment by mineyoshikawasnow** [comment]
Hayao氏のPull Reqが原因だと思われます。

**Comment by Hayao0819** [comment]
e78da751727ba1e8391868c616329d3d17681847 で既に修正済みです

**Comment by Hayao0819** [comment]
該当コミットがマージされていませんでした。
f3441cea324df5574cdc48386a86c8ea1bcdd256 でmasterにマージしました。

**Comment by Hayao0819** [comment]
エラーが発生するタイミングが異なったのは`remove`関数が呼び出されたときにエラーが発生するからです
