### ISSUE TITLE
ライブ起動時 HostNameの表記を変更すべきかも？

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#30]
おそらくHostNameに設定されているためそちらを参照している部分に影響している予想している

HostName
ターミナル
Xfceについて

Fedora派生ではあるものFedoraとはだいぶ違うものにFedoraという表記をするのはどうだろう？

可能であればLiveなどの表記にしたほうが誤解がなさそう

![image](https://user-images.githubusercontent.com/50263013/113466648-6536ab00-9478-11eb-90a2-bc59babd445d.png)
![image](https://user-images.githubusercontent.com/50263013/113466713-d37b6d80-9478-11eb-8258-bc87f8b5c126.png)

**Comment by naoko1010hh** [comment]
該当ISO SereneLinux-34-serene-ja-2021.04.01-098c2a0-x86_64.iso

**Comment by mineyoshikawasnow** [comment]
開発版のまま放置しててやつですね..。
子宮修正ですね...

**Comment by mineyoshikawasnow** [comment]
![image](https://user-images.githubusercontent.com/39451248/113479000-4c091b00-94c7-11eb-9eaf-352d7c49e1bb.png)
変更したので閉じますを
