### ISSUE TITLE
Cairo-DockのアプリケーションメニューがGnomeアイコン

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#34]
アイコンがGnomeになっています。
アプリケーションメニューであれば、左上にパネルのxfce4-popup-whiskermenuと同じSereneLinuxアイコンにスべきでしょう

個人的はアプリケーションメニューやログアウト、ヘルプなどは必要ないかなと思っています。

![スクリーンショット_2021-04-04_00-14-32](https://user-images.githubusercontent.com/50263013/113483365-fe4bdd00-94dd-11eb-9eea-f28b5ccba832.png)

検証ISO 内部バージョン
SereneLinux-34-serene-ja-2021.04.03-f37cb43-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 2GB
仮想VDI 8GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
fixed 3914358
