### ISSUE TITLE
htopコマンドを追加してほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#35]
システムモニターコマンドであるhtopコマンドが初期インストールされていると使いやすいと思います。可能であれば初期インストールされていると良い
![スクリーンショット_2021-04-04_00-20-04](https://user-images.githubusercontent.com/50263013/113483742-f1c88400-94df-11eb-8dd6-f5a5a3442b64.png)

検証ISO 内部バージョン
SereneLinux-34-serene-ja-2021.04.03-f37cb43-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 2GB
仮想VDI 8GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
3914358
added htop.
