### ISSUE TITLE
serene  スリープ復帰後のログイン画面が古臭い

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/LFBS#4]
sereneチャンネルでビルドしたISOを実機にインストールして使用していますが、スリープから復帰した後のログイン画面が古臭いです....　sereneの雰囲気に合わないので変更してほしいです。

**Comment by naoko1010hh** [comment]
スクリーンショットか写真あげてもらえると助かります。m(_ _)m

**Comment by 32x-k** [comment]
![IMG20201021210957.jpg](https://user-images.githubusercontent.com/59412454/96717696-d78f6380-13e1-11eb-9f94-91f8f96763ef.jpg) こんな感じです。

**Comment by mineyoshikawasnow** [comment]
至急修正します。

**Comment by mineyoshikawasnow** [comment]
![scrsaver2](https://user-images.githubusercontent.com/39451248/96732816-b9326380-13f3-11eb-9606-2a61487b6556.png)

これでどうでしょうか?

**Comment by mineyoshikawasnow** [comment]
修正されたので閉じます。
