### ISSUE TITLE
何故か動かない

### ISSUE THREAD

**Issue by ghost** [FascodeNet/LFBS#42]
./lubs: line 224: msg_warn: command not foundと表示されて終了してしまう

OS: Ubuntu 20.04.3 LTS Focal Fossa

**Comment by xenonwarefounder** [comment]
./lubs: line 224: msg_warn: command not foundと表示されて終了してしまう

OS: Ubuntu 20.04.3 LTS Focal Fossa

**Comment by mineyoshikawasnow** [comment]
リポジトリ間違えてますよ。
