### ISSUE TITLE
dnfのグラフィカルフロントエンドが正常に動作しない

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/LFBS#5]
![image](https://user-images.githubusercontent.com/59412454/96873448-e8a6a600-14af-11eb-86d2-180450af1715.png)
ソフトの起動自体は問題なくできますが、ミラーとの同期がいくら待っても終わりません。ウィンドウを閉じようとすると「応答がありません」と出るのでフリーズしてるみたいです。

**Comment by mineyoshikawasnow** [comment]
Discoverに変えました
![image](https://user-images.githubusercontent.com/39451248/96884740-ccf5cc80-14bc-11eb-880e-3ada113ca13e.png)
