### ISSUE TITLE
ライブ環境　インストーラーアイコンがCalamarese

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#7]
下記のようにアイコンがデフォルトのままなのでSereneLinuxBeta7とかのインストーラーアイコンにすべきでしょう

![image](https://user-images.githubusercontent.com/50263013/103153335-35ba3780-47d3-11eb-8a18-003b3b0e2e48.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
アイコンどこだっけ?

**Comment by mineyoshikawasnow** [comment]
![picture](https://user-images.githubusercontent.com/39451248/103272686-d93c5f80-4a00-11eb-9208-b93b1e628593.png)
ea2246c
