### ISSUE TITLE
ライブ環境　放置するとロックされてログインできなくなる

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#8]
ライブ環境で放置するとロックされパスワードが不明な場合操作不能になるので不親切です。ライブ環境ではロックされないように修正お願いします。

![image](https://user-images.githubusercontent.com/50263013/103153566-ce04ec00-47d4-11eb-9a14-8851ec7880a2.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
あれ未修正だったか...

**Comment by mineyoshikawasnow** [comment]
https://github.com/FascodeNet/LFBS/commit/011bb8ea93917a6083d8bee1270d397acd9b928a

**Comment by mineyoshikawasnow** [comment]
治ったのでclose

**Comment by naoko1010hh** [comment]
![VirtualBox_Serene F _28_12_2020_23_30_13](https://user-images.githubusercontent.com/50263013/103220939-cc6a2e00-4964-11eb-912d-5bb6966bf6a7.png)

修正済みとのことでしたがこちらの内部ISOでも同様の問題が発生しました。
SereneLinux-33-serene-ja-2020.12.28-cc5253d-x86_64.iso

**Comment by mineyoshikawasnow** [comment]
https://github.com/FascodeNet/LFBS/commit/8f5bbd2b71162a3e57c9431fed5aedcd3e0f2bf0

**Comment by naoko1010hh** [comment]
放置すると似たような問題が再度発生、、、
qt版に変わったことで2重ロックがかかるという恐ろしい事態へ

下記のロック画面はライブのパスワード知っていれば1個目のロックは解除できます。
↓
![VirtualBox_serene_04_04_2021_01_00_36](https://user-images.githubusercontent.com/50263013/113484128-a9aa6100-94e1-11eb-965b-89a547a4f886.png)
その後、入力不可の下記の画面がでて積みます。
↓
![VirtualBox_serene_04_04_2021_01_00_53](https://user-images.githubusercontent.com/50263013/113484130-aca55180-94e1-11eb-9cbc-713862b75927.png)



検証ISO 内部バージョン
SereneLinux-34-serene-ja-2021.04.03-f37cb43-x86_64.iso

検証環境　仮想

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 2GB
仮想VDI 8GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
二重ロック、qmlロック共にかからなくなりました
