### ISSUE TITLE
一部のお気に入りのアプリケーションが設定されていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LFBS#9]
お気に入りアプリケーションが設定されていないため正常に動作しないgoogleショートカットが存在する

![image](https://user-images.githubusercontent.com/50263013/103153692-b1b57f00-47d5-11eb-9ac0-7e14aa62d2c1.png)

![image](https://user-images.githubusercontent.com/50263013/103153641-4cfa2480-47d5-11eb-8fd4-d976e96da0c8.png)

kokkiemouseビルド内部
SereneLinux-33-serene-ja-2020.12.26-x86_64.iso

検証環境　仮想　ライブ環境

VirtualBox仮想環境
アーキテクチャ 64bit
RAM 4GB
仮想VDI 20GB

ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by mineyoshikawasnow** [comment]
具体的に書いてクレメンス

**Comment by naoko1010hh** [comment]
下部タスクバーのGoogleショートカットのランチャーからGmailを
起動したところお気に入りのアプリケーションを選択してくださいと表示されたため
お気に入りアプリケーションが設定されているか検証したところ
ウェブブラウザーとメールが設定されていないため
お気に入りアプリケーションの一部が設定できていないと思われます。

**Comment by mineyoshikawasnow** [comment]
動い田所さんなので閉じます。

**Comment by naoko1010hh** [comment]
内部バージョンの下記にて同様の問題が発生している模様
SereneLinux-34-serene-ja-2021.04.01-098c2a0-x86_64.iso
![image](https://user-images.githubusercontent.com/50263013/113466346-0708c880-9476-11eb-9bc3-31e92aba541a.png)

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend
仮想環境
アーキテクチャ 64bit
RAM 2048MB

**Comment by mineyoshikawasnow** [comment]
これ設定し忘れてた／(^o^)＼
子宮修正します

**Comment by naoko1010hh** [comment]
了解しました

**Comment by mineyoshikawasnow** [comment]
修正完了につきcloseします
